train:
  epochs: 10
  batch: 32

  scheduler: linear
  warmup: 0.1

test:
  batch: 256

model:
  dim: 32
  max_len: 512

  embedding:
    size: 1000
    pad: 0

  positional:
    dropout: 0.3

  encoder:
    layer_num: 4
    head_num: 2
    fc_dim: 64
    dropout: 0.1

    gate:
      name: "model.gate.SoftGate"
      embed_dim: 32


  decoder:
    layer_num: 2
    head_num: 4
    fc_dim: 64
    dropout: 0.1

  classifier:
    dropout: 0.3
